// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​p​p​l​i​c​a​t​i​o​n​s
	 */
	APPS: string
}

export type TranslationFunctions = {
	/**
	 * Applications
	 */
	APPS: () => LocalizedString
}

export type Formatters = {}
