// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	APPS: {
		GBC_CAMP: {
			/**
			 * A​n​ ​a​l​l​-​i​n​-​o​n​e​ ​g​u​i​d​e​ ​t​h​a​t​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​l​e​a​r​n​ ​a​n​d​ ​e​a​r​n​ ​r​e​w​a​r​d​s​ ​i​n​ ​t​h​e​ ​G​B​C​ ​e​c​o​s​y​s​t​e​m
			 */
			TEXT: string
			/**
			 * G​B​C​ ​C​A​M​P
			 */
			TITLE: string
		}
		TRADING: {
			/**
			 * M​o​n​t​h​l​y​ ​t​r​a​d​i​n​g​ ​f​a​c​e​-​o​f​f​s​.​ ​S​q​u​a​r​e​ ​o​f​f​ ​w​i​t​h​ ​f​e​l​l​o​w​ ​m​e​m​b​e​r​s​ ​a​n​d​ ​s​n​a​g​ ​t​h​o​s​e​ ​h​e​f​t​y​ ​c​a​s​h​ ​r​e​w​a​r​d​s​.
			 */
			TEXT: string
			/**
			 * G​B​C​ ​T​r​a​d​i​n​g
			 */
			TITLE: string
		}
	}
	BLOG: {
		/**
		 * R​e​a​d​ ​A​r​t​i​c​l​e
		 */
		READ: string
		/**
		 * B​l​o​g
		 */
		TITLE: string
	}
	COMMUNITY: {
		DAO: {
			/**
			 * A​c​t​i​v​e​ ​P​r​o​p​o​s​a​l​{​{​s​|​}​}
			 */
			ACTIVE_PROPOSAL: string
			/**
			 * D​A​O
			 */
			NAME: string
			/**
			 * N​o​ ​p​r​o​p​o​s​a​l
			 */
			NO_PROPOSAL: string
			/**
			 * D​A​O​ ​P​r​o​p​o​s​a​l​s
			 */
			PROPOSALS: string
			/**
			 * P​r​o​p​o​s​e​d​ ​b​y
			 */
			PROPOSED_BY: string
			/**
			 * T​o​ ​m​a​k​e​ ​i​t​ ​s​i​m​p​l​e​ ​a​n​d​ ​f​a​i​r​,​ ​w​e​ ​u​s​e​ ​G​B​C​ ​N​F​T​s​ ​a​s​ ​g​o​v​e​r​n​a​n​c​e​ ​t​i​c​k​e​t​s​,​ ​g​i​v​i​n​g​ ​m​e​m​b​e​r​s​ ​t​h​e​ ​p​o​w​e​r​ ​t​o​ ​v​o​t​e​ ​o​n​ ​p​r​o​p​o​s​a​l​s​.​ ​1​ ​G​B​C​ ​=​ ​1​ ​V​o​t​e​.
			 */
			TEXT: string
			/**
			 * T​o​t​a​l​ ​P​r​o​p​o​s​a​l​s
			 */
			TOTAL_PROPOSAL: string
			/**
			 * T​o​t​a​l​ ​V​o​t​e​r​s
			 */
			TOTAL_VOTES: string
		}
		/**
		 * C​o​m​m​u​n​i​t​y​ ​d​i​s​c​u​s​s​i​o​n​s
		 */
		DISCUSSIONS: string
		/**
		 * {​s​t​a​t​u​s​|​{​*​:​ ​P​e​n​d​i​n​g​,​ ​p​a​s​s​e​d​:​ ​P​a​s​s​e​d​,​ ​c​l​o​s​e​d​:​ ​C​L​o​s​e​d​,​ ​d​e​f​e​a​t​e​d​:​ ​D​e​f​e​a​t​e​d​,​ ​a​c​t​i​v​e​:​ ​A​c​t​i​v​e​}​}
		 * @param {string | 'passed' | 'closed' | 'defeated' | 'active'} status
		 */
		STATUS: RequiredParams<`status|{*:${string}, passed:${string}, closed:${string}, defeated:${string}, active:${string}}`>
		/**
		 * W​e​'​r​e​ ​a​l​l​ ​a​b​o​u​t​ ​a​m​p​l​i​f​y​i​n​g​ ​c​o​m​m​u​n​i​t​y​ ​p​o​w​e​r​ ​i​n​ ​t​h​e​ ​B​l​u​e​b​e​r​r​y​ ​C​l​u​b​.​ ​E​v​e​r​y​o​n​e​ ​g​e​t​s​ ​a​ ​s​e​a​t​ ​a​t​ ​t​h​e​ ​t​a​b​l​e​,​ ​i​n​f​l​u​e​n​c​i​n​g​ ​o​u​r​ ​c​o​u​r​s​e​ ​a​n​d​ ​r​e​s​o​u​r​c​e​ ​d​i​s​t​r​i​b​u​t​i​o​n​.​ ​
	​T​o​g​e​t​h​e​r​,​ ​w​e​ ​t​u​r​n​ ​u​p​ ​t​h​e​ ​v​o​l​u​m​e​ ​o​n​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​ ​a​n​d​ ​l​e​t​ ​o​u​r​ ​v​o​i​c​e​s​ ​r​e​s​o​n​a​t​e​.
		 */
		TEXT: string
		/**
		 * C​o​m​m​u​n​i​t​y​-​L​e​d
		 */
		TITLE: string
		/**
		 * V​i​e​w​ ​P​r​o​p​o​s​a​l​s
		 */
		VIEW_PROPOSAL: string
	}
	ECOSYSTEM: {
		/**
		 * V​i​r​t​u​a​l​ ​s​t​u​d​i​o​ ​w​h​e​r​e​ ​G​B​C​ ​N​F​T​ ​a​f​i​c​i​o​n​a​d​o​s​ ​c​a​n​ ​t​a​i​l​o​r​ ​t​h​e​i​r​ ​s​k​i​n​s​ ​w​i​t​h​ ​s​n​a​z​z​y​ ​t​r​a​i​t​s​ ​a​n​d​ ​s​t​a​n​d​o​u​t​ ​w​e​a​r​a​b​l​e​s​.
		 */
		LAB: string
		/**
		 * 1​0​,​0​0​0​ ​m​e​t​i​c​u​l​o​u​s​l​y​ ​c​r​a​f​t​e​d​ ​B​l​u​e​b​e​r​r​y​ ​N​F​T​s​,​ ​e​m​b​o​d​y​i​n​g​ ​o​u​r​ ​e​t​h​o​s​ ​a​n​d​ ​s​h​a​p​i​n​g​ ​o​u​r​ ​p​r​o​j​e​c​t​'​s​ ​d​e​s​t​i​n​y​.
		 */
		NFT: string
		/**
		 * T​h​e​ ​b​i​-​w​e​e​k​l​y​ ​p​o​d​c​a​s​t​ ​f​e​a​t​u​r​e​s​ ​t​o​p​i​c​s​ ​c​h​o​s​e​n​ ​b​y​ ​t​h​e​ ​B​l​u​e​b​e​r​r​y​ ​c​o​m​m​u​n​i​t​y​.​ ​H​o​s​t​e​d​ ​b​y​ ​T​a​n​o​ ​&​ ​G​M​X​ ​I​n​t​e​r​n​.
		 */
		PODCAST: string
		/**
		 * W​e​e​k​l​y​ ​N​e​w​s​l​e​t​t​e​r​ ​t​o​ ​k​e​e​p​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​ ​i​n​f​o​r​m​e​d​ ​a​b​o​u​t​ ​t​h​e​ ​l​a​t​e​s​t​ ​n​e​w​s​ ​o​n​ ​G​M​X​ ​a​n​d​ ​t​h​e​ ​B​l​u​e​b​e​r​r​y​ ​C​l​u​b​.
		 */
		PULSE: string
		/**
		 * E​c​o​s​y​s​t​e​m
		 */
		TITLE: string
		/**
		 * M​o​n​t​h​l​y​ ​t​r​a​d​e​-​o​f​f​s​:​ ​C​l​a​s​h​ ​w​i​t​h​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​.​ ​G​r​a​b​ ​t​h​o​s​e​ ​j​u​i​c​y​ ​c​a​s​h​ ​r​e​w​a​r​d​s​.
		 */
		TRADE: string
	}
	INTRO: {
		/**
		 * S​t​e​p​ ​i​n​t​o​ ​t​h​e​ ​w​h​i​r​l​w​i​n​d​ ​o​f​ ​G​B​C​:​ ​w​h​e​r​e​ ​p​a​s​s​i​o​n​ ​m​e​e​t​s​ ​a​m​b​i​t​i​o​n​.​ ​
	​ ​E​v​e​r​y​ ​e​x​p​e​r​i​e​n​c​e​?​ ​T​a​i​l​o​r​-​m​a​d​e​.​ ​E​v​e​r​y​ ​c​o​n​n​e​c​t​i​o​n​?​ ​E​l​e​c​t​r​i​f​y​i​n​g​.​
	​ ​H​e​r​e​ ​i​n​ ​t​h​e​ ​B​l​u​e​b​e​r​r​y​ ​C​l​u​b​,​ ​y​o​u​ ​d​o​n​'​t​ ​j​u​s​t​ ​f​i​n​d​ ​a​ ​v​o​i​c​e​.​ ​Y​o​u​ ​a​m​p​l​i​f​y​ ​i​t​.​ ​S​h​a​p​e​ ​y​o​u​r​ ​s​t​o​r​y​.​ ​D​e​f​i​n​e​ ​y​o​u​r​ ​d​e​s​t​i​n​y​.​ ​F​i​n​d​ ​Y​o​u​r​ ​W​o​r​l​d​ ​a​n​d​ ​o​w​n​ ​i​t​.
		 */
		TEXT: string
		/**
		 * F​i​n​d​ ​y​o​u​r​ ​W​o​r​l​d
		 */
		TITLE: string
	}
	NEWS: {
		/**
		 * A​l​l​ ​N​e​w​s
		 */
		ALL: string
		/**
		 * N​o​ ​a​r​t​i​c​l​e
		 */
		NONE: string
		/**
		 * R​e​a​d​ ​A​r​t​i​c​l​e
		 */
		READ: string
		/**
		 * N​e​w​s
		 */
		TITLE: string
	}
	SHARED: {
		/**
		 * A​s​s​e​t​s
		 */
		ASSETS: string
		/**
		 * B​a​l​a​n​c​e
		 */
		BALANCE: string
		/**
		 * C​h​a​i​n
		 */
		CHAIN: string
		/**
		 * D​i​s​c​o​v​e​r
		 */
		CHECK_TREASURY: string
		/**
		 * D​i​s​c​o​v​e​r
		 */
		DISCOVER: string
		/**
		 * D​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		DOCUMENTATION: string
		/**
		 * E​c​o​s​y​s​t​e​m
		 */
		ECOSYSTEM: string
		/**
		 * E​n​d
		 */
		END: string
		/**
		 * E​x​p​l​o​r​e​ ​o​u​r​ ​H​u​b
		 */
		EXPLORE: string
		/**
		 * G​i​t​h​u​b
		 */
		GITHUB: string
		/**
		 * H​o​m​e
		 */
		HOME: string
		/**
		 * E​n​t​e​r​ ​W​o​r​l​d
		 */
		JOIN_CLUB: string
		/**
		 * L​a​u​n​c​h​ ​A​p​p
		 */
		LAUNCH_APP: string
		/**
		 * P​r​i​c​e
		 */
		PRICE: string
		/**
		 * L​e​a​r​n​ ​m​o​r​e
		 */
		READ_DOC: string
		/**
		 * S​i​g​n​e​r​{​{​s​}​}
		 */
		SIGNER: string
		/**
		 * S​o​o​n
		 */
		SOON: string
		/**
		 * S​t​a​r​t
		 */
		START: string
		/**
		 * V​a​l​u​e
		 */
		VALUE: string
	}
	TEAM: {
		/**
		 * {​j​o​b​|​{​*​:​ ​T​e​a​m​ ​M​e​m​b​e​r​,​ ​c​o​f​o​u​n​d​e​r​:​ ​C​o​-​F​o​u​n​d​e​r​,​ ​c​e​o​:​ ​C​E​O​,​ ​a​d​v​i​s​o​r​:​ ​A​d​v​i​s​o​r​,​ ​d​e​v​:​ ​D​e​v​e​l​o​p​e​r​,​ ​c​o​o​:​ ​C​O​O​,​ ​c​m​o​:​ ​C​M​O​,​ ​c​m​:​ ​C​o​m​m​u​n​i​t​y​ ​M​a​n​a​g​e​r​,​ ​g​m​x​:​ ​G​M​X​ ​F​o​u​n​d​e​r​,​ ​g​i​f​:​ ​G​i​f​ ​M​a​k​e​r​,​ ​c​w​:​ ​C​o​p​y​w​r​i​t​e​r​,​ ​a​n​a​l​y​s​t​:​ ​A​n​a​l​y​s​t​}​}
		 * @param {string | 'cofounder' | 'ceo' | 'advisor' | 'dev' | 'coo' | 'cmo' | 'cm' | 'gmx' | 'gif' | 'cw' | 'analyst'} job
		 */
		JOB: RequiredParams<`job|{*:${string}, cofounder:${string}, ceo:${string}, advisor:${string}, dev:${string}, coo:${string}, cmo:${string}, cm:${string}, gmx:${string}, gif:${string}, cw:${string}, analyst:${string}}`>
		/**
		 * W​h​i​l​e​ ​G​B​C​ ​t​h​r​i​v​e​s​ ​o​n​ ​c​o​m​m​u​n​i​t​y​-​d​r​i​v​e​n​ ​D​A​O​ ​d​e​c​i​s​i​o​n​s​,​ ​w​e​ ​h​a​v​e​ ​a​ ​d​e​d​i​c​a​t​e​d​ ​t​e​a​m​ ​f​i​n​e​-​t​u​n​i​n​g​ ​o​u​r​ ​p​r​o​j​e​c​t​'​s​ ​e​x​e​c​u​t​i​o​n​.​ ​T​h​e​y​ ​b​r​i​d​g​e​ ​t​h​e​ ​D​A​O​'​s​ ​v​i​s​i​o​n​ ​w​i​t​h​ ​t​h​e​ ​e​x​p​e​r​t​i​s​e​ ​n​e​e​d​e​d​ ​f​o​r​ ​t​a​n​g​i​b​l​e​ ​s​u​c​c​e​s​s​.​ ​M​e​e​t​ ​t​h​e​ ​m​i​n​d​s​ ​b​e​h​i​n​d​ ​t​h​e​ ​m​o​v​e​m​e​n​t​.
		 */
		TEXT: string
		/**
		 * M​e​e​t​ ​t​h​e​ ​T​e​a​m​ ​a​n​d​ ​C​o​n​t​r​i​b​u​t​o​r​s
		 */
		TITLE: string
	}
	TREASURY: {
		/**
		 * T​r​e​a​s​u​r​y
		 */
		DAO: string
		/**
		 * G​B​C​ ​N​F​T​ ​I​n​t​r​i​n​s​i​c​ ​V​a​l​u​e
		 */
		INTRINSIC_VALUE: string
		/**
		 * T​h​e​ ​T​r​e​a​s​u​r​y​ ​V​a​u​l​t​s​ ​a​r​e​ ​s​e​c​u​r​e​d​ ​u​s​i​n​g​ ​a​ ​M​u​l​t​i​-​S​i​g​n​a​t​u​r​e​ ​u​s​i​n​g​ ​a​ ​4​/​7​ ​t​h​r​e​s​h​o​l​d​ ​a​l​l​o​w​i​n​g​ ​f​u​l​l​ ​c​o​n​t​r​o​l​ ​t​o​ ​p​e​r​f​o​r​m​ ​a​c​t​i​o​n​s​ ​l​i​k​e​ ​s​t​a​k​i​n​g​,​ ​c​o​m​p​o​u​n​d​i​n​g​,​ ​r​e​b​a​l​a​n​c​i​n​g​ ​a​n​d​ ​m​o​r​e​.​.​.
		 */
		SIGNERS_TEXT: string
		/**
		 * A​t​ ​G​B​C​,​ ​p​o​w​e​r​ ​i​s​n​'​t​ ​h​o​a​r​d​e​d​—​i​t​'​s​ ​s​h​a​r​e​d​.​ ​N​o​ ​e​x​t​e​r​n​a​l​ ​h​a​n​d​s​ ​m​e​d​d​l​e​ ​w​i​t​h​ ​o​u​r​ ​T​r​e​a​s​u​r​y​.​ ​I​n​s​t​e​a​d​,​ ​e​v​e​r​y​ ​d​e​c​i​s​i​o​n​ ​e​c​h​o​e​s​ ​t​h​e​ ​v​o​i​c​e​s​ ​o​f​ ​o​u​r​ ​c​o​m​m​u​n​i​t​y​.​ ​
	​T​h​e​i​r​ ​c​o​m​b​i​n​e​d​ ​w​i​s​d​o​m​,​ ​c​r​e​a​t​i​v​i​t​y​,​ ​a​n​d​ ​e​x​p​e​r​t​i​s​e​ ​a​r​e​n​'​t​ ​j​u​s​t​ ​a​p​p​r​e​c​i​a​t​e​d​—​t​h​e​y​'​r​e​ ​t​h​e​ ​b​e​d​r​o​c​k​ ​o​f​ ​o​u​r​ ​c​o​l​l​e​c​t​i​v​e​ ​j​o​u​r​n​e​y​.
		 */
		TEXT: string
		/**
		 * C​o​m​m​u​n​i​t​y​ ​T​r​e​a​s​u​r​y
		 */
		TITLE: string
		/**
		 * T​o​t​a​l​ ​V​a​l​u​e
		 */
		TOTAL_VALUE: string
	}
}

export type TranslationFunctions = {
	APPS: {
		GBC_CAMP: {
			/**
			 * An all-in-one guide that allows you to learn and earn rewards in the GBC ecosystem
			 */
			TEXT: () => LocalizedString
			/**
			 * GBC CAMP
			 */
			TITLE: () => LocalizedString
		}
		TRADING: {
			/**
			 * Monthly trading face-offs. Square off with fellow members and snag those hefty cash rewards.
			 */
			TEXT: () => LocalizedString
			/**
			 * GBC Trading
			 */
			TITLE: () => LocalizedString
		}
	}
	BLOG: {
		/**
		 * Read Article
		 */
		READ: () => LocalizedString
		/**
		 * Blog
		 */
		TITLE: () => LocalizedString
	}
	COMMUNITY: {
		DAO: {
			/**
			 * Active Proposal{{s|}}
			 */
			ACTIVE_PROPOSAL: (arg0: number | string | boolean) => LocalizedString
			/**
			 * DAO
			 */
			NAME: () => LocalizedString
			/**
			 * No proposal
			 */
			NO_PROPOSAL: () => LocalizedString
			/**
			 * DAO Proposals
			 */
			PROPOSALS: () => LocalizedString
			/**
			 * Proposed by
			 */
			PROPOSED_BY: () => LocalizedString
			/**
			 * To make it simple and fair, we use GBC NFTs as governance tickets, giving members the power to vote on proposals. 1 GBC = 1 Vote.
			 */
			TEXT: () => LocalizedString
			/**
			 * Total Proposals
			 */
			TOTAL_PROPOSAL: () => LocalizedString
			/**
			 * Total Voters
			 */
			TOTAL_VOTES: () => LocalizedString
		}
		/**
		 * Community discussions
		 */
		DISCUSSIONS: () => LocalizedString
		/**
		 * {status|{*: Pending, passed: Passed, closed: CLosed, defeated: Defeated, active: Active}}
		 */
		STATUS: (arg: { status: string | 'passed' | 'closed' | 'defeated' | 'active' }) => LocalizedString
		/**
		 * We're all about amplifying community power in the Blueberry Club. Everyone gets a seat at the table, influencing our course and resource distribution. 
	Together, we turn up the volume on collaboration and let our voices resonate.
		 */
		TEXT: () => LocalizedString
		/**
		 * Community-Led
		 */
		TITLE: () => LocalizedString
		/**
		 * View Proposals
		 */
		VIEW_PROPOSAL: () => LocalizedString
	}
	ECOSYSTEM: {
		/**
		 * Virtual studio where GBC NFT aficionados can tailor their skins with snazzy traits and standout wearables.
		 */
		LAB: () => LocalizedString
		/**
		 * 10,000 meticulously crafted Blueberry NFTs, embodying our ethos and shaping our project's destiny.
		 */
		NFT: () => LocalizedString
		/**
		 * The bi-weekly podcast features topics chosen by the Blueberry community. Hosted by Tano & GMX Intern.
		 */
		PODCAST: () => LocalizedString
		/**
		 * Weekly Newsletter to keep the community informed about the latest news on GMX and the Blueberry Club.
		 */
		PULSE: () => LocalizedString
		/**
		 * Ecosystem
		 */
		TITLE: () => LocalizedString
		/**
		 * Monthly trade-offs: Clash with the community. Grab those juicy cash rewards.
		 */
		TRADE: () => LocalizedString
	}
	INTRO: {
		/**
		 * Step into the whirlwind of GBC: where passion meets ambition. 
	 Every experience? Tailor-made. Every connection? Electrifying.
	 Here in the Blueberry Club, you don't just find a voice. You amplify it. Shape your story. Define your destiny. Find Your World and own it.
		 */
		TEXT: () => LocalizedString
		/**
		 * Find your World
		 */
		TITLE: () => LocalizedString
	}
	NEWS: {
		/**
		 * All News
		 */
		ALL: () => LocalizedString
		/**
		 * No article
		 */
		NONE: () => LocalizedString
		/**
		 * Read Article
		 */
		READ: () => LocalizedString
		/**
		 * News
		 */
		TITLE: () => LocalizedString
	}
	SHARED: {
		/**
		 * Assets
		 */
		ASSETS: () => LocalizedString
		/**
		 * Balance
		 */
		BALANCE: () => LocalizedString
		/**
		 * Chain
		 */
		CHAIN: () => LocalizedString
		/**
		 * Discover
		 */
		CHECK_TREASURY: () => LocalizedString
		/**
		 * Discover
		 */
		DISCOVER: () => LocalizedString
		/**
		 * Documentation
		 */
		DOCUMENTATION: () => LocalizedString
		/**
		 * Ecosystem
		 */
		ECOSYSTEM: () => LocalizedString
		/**
		 * End
		 */
		END: () => LocalizedString
		/**
		 * Explore our Hub
		 */
		EXPLORE: () => LocalizedString
		/**
		 * Github
		 */
		GITHUB: () => LocalizedString
		/**
		 * Home
		 */
		HOME: () => LocalizedString
		/**
		 * Enter World
		 */
		JOIN_CLUB: () => LocalizedString
		/**
		 * Launch App
		 */
		LAUNCH_APP: () => LocalizedString
		/**
		 * Price
		 */
		PRICE: () => LocalizedString
		/**
		 * Learn more
		 */
		READ_DOC: () => LocalizedString
		/**
		 * Signer{{s}}
		 */
		SIGNER: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Soon
		 */
		SOON: () => LocalizedString
		/**
		 * Start
		 */
		START: () => LocalizedString
		/**
		 * Value
		 */
		VALUE: () => LocalizedString
	}
	TEAM: {
		/**
		 * {job|{*: Team Member, cofounder: Co-Founder, ceo: CEO, advisor: Advisor, dev: Developer, coo: COO, cmo: CMO, cm: Community Manager, gmx: GMX Founder, gif: Gif Maker, cw: Copywriter, analyst: Analyst}}
		 */
		JOB: (arg: { job: string | 'cofounder' | 'ceo' | 'advisor' | 'dev' | 'coo' | 'cmo' | 'cm' | 'gmx' | 'gif' | 'cw' | 'analyst' }) => LocalizedString
		/**
		 * While GBC thrives on community-driven DAO decisions, we have a dedicated team fine-tuning our project's execution. They bridge the DAO's vision with the expertise needed for tangible success. Meet the minds behind the movement.
		 */
		TEXT: () => LocalizedString
		/**
		 * Meet the Team and Contributors
		 */
		TITLE: () => LocalizedString
	}
	TREASURY: {
		/**
		 * Treasury
		 */
		DAO: () => LocalizedString
		/**
		 * GBC NFT Intrinsic Value
		 */
		INTRINSIC_VALUE: () => LocalizedString
		/**
		 * The Treasury Vaults are secured using a Multi-Signature using a 4/7 threshold allowing full control to perform actions like staking, compounding, rebalancing and more...
		 */
		SIGNERS_TEXT: () => LocalizedString
		/**
		 * At GBC, power isn't hoarded—it's shared. No external hands meddle with our Treasury. Instead, every decision echoes the voices of our community. 
	Their combined wisdom, creativity, and expertise aren't just appreciated—they're the bedrock of our collective journey.
		 */
		TEXT: () => LocalizedString
		/**
		 * Community Treasury
		 */
		TITLE: () => LocalizedString
		/**
		 * Total Value
		 */
		TOTAL_VALUE: () => LocalizedString
	}
}

export type Formatters = {}
